<?php
return array(
    'yxd_services_models_account'                  => array('db'=>'club','table'=>'account'),
    'yxd_services_models_accountban'               => array('db'=>'club','table'=>'account_ban'),
    'yxd_services_models_accountcircle'            => array('db'=>'club','table'=>'account_circle'),
    'yxd_services_models_accountcredithistory'     => array('db'=>'club','table'=>'account_credit_history'),
    'yxd_services_models_accountfollow'            => array('db'=>'club','table'=>'account_follow'),
    'yxd_services_models_accountgroup'             => array('db'=>'club','table'=>'account_group'),
    'yxd_services_models_accountgrouplink'         => array('db'=>'club','table'=>'account_group_link'),
    'yxd_services_models_accountsession'           => array('db'=>'club','table'=>'account_session'),
    'yxd_services_models_accountshieldhistory'     => array('db'=>'club','table'=>'account_shield_history'),
    'yxd_services_models_accountthirdlogin'        => array('db'=>'club','table'=>'account_thirdlogin'),
    'yxd_services_models_activity'				   => array('db'=>'club','table'=>'activity'),
    'yxd_services_models_activityask'              => array('db'=>'club','table'=>'activity_ask'),
    'yxd_services_models_activityaskaccount'       => array('db'=>'club','table'=>'activity_ask_account'),
    'yxd_services_models_activityaskquestion'	   => array('db'=>'club','table'=>'activity_ask_question'),
    'yxd_services_models_activityhunt'			   => array('db'=>'club','table'=>'activity_hunt'),
    'yxd_services_models_activityhuntaccount'	   => array('db'=>'club','table'=>'activity_hunt_account'),
    'yxd_services_models_activityprize'			   => array('db'=>'club','table'=>'activity_prize'),
    'yxd_services_models_atme'					   => array('db'=>'club','table'=>'atme'),
    'yxd_services_models_chatlog'				   => array('db'=>'club','table'=>'chat_log'),
    'yxd_services_models_chatuser'				   => array('db'=>'club','table'=>'chat_user'),
    'yxd_services_models_checkinfo'				   => array('db'=>'club','table'=>'checkinfo'),
    'yxd_services_models_checkinfolimit'		   => array('db'=>'club','table'=>'checkinfo_limit'),
    'yxd_services_models_comment'				   => array('db'=>'club','table'=>'comment'),
    'yxd_services_models_creditaccount'            => array('db'=>'club','table'=>'credit_account'),
    'yxd_services_models_creditlevel'              => array('db'=>'club','table'=>'credit_level'),
    'yxd_services_models_creditsetting'            => array('db'=>'club','table'=>'credit_setting'),
    'yxd_services_models_feedatme'                 => array('db'=>'club','table'=>'feed_atme'),
    'yxd_services_models_feedgamecircle'           => array('db'=>'club','table'=>'feed_gamecircle'),
    'yxd_services_models_feedgamecirclecount'      => array('db'=>'club','table'=>'feed_gamecircle_count'),
    'yxd_services_models_feeduser'                 => array('db'=>'club','table'=>'feed_user'),
    'yxd_services_models_feeduserflow'             => array('db'=>'club','table'=>'feed_userflow'),
    'yxd_services_models_forum'                    => array('db'=>'club','table'=>'forum'),
    'yxd_services_models_forumchannel'             => array('db'=>'club','table'=>'forum_channel'),
    
    'yxd_services_models_forumnotice'              => array('db'=>'club','table'=>'forum_notice'),
    'yxd_services_models_forumpost'                => array('db'=>'club','table'=>'forum_post'),
    'yxd_services_models_forumsetbestmax'          => array('db'=>'club','table'=>'forum_setbest_max'),
    'yxd_services_models_forumtopic'               => array('db'=>'club','table'=>'forum_topic'),
    'yxd_services_models_gamecontrol'              => array('db'=>'club','table'=>'game_control'),
    'yxd_services_models_gamecredit'               => array('db'=>'club','table'=>'game_credit'),
    'yxd_services_models_gamedownloadadvcount'     => array('db'=>'club','table'=>'game_download_adv_count'),
    'yxd_services_models_gamedownloadcount'        => array('db'=>'club','table'=>'game_download_count'),
    'yxd_services_models_giftaccount'              => array('db'=>'club','table'=>'gift_account'),
    'yxd_services_models_giftreserve'              => array('db'=>'club','table'=>'gift_reserve'),
    'yxd_services_models_giftbag'                  => array('db'=>'club','table'=>'giftbag'),
    'yxd_services_models_giftbagappoint'           => array('db'=>'club','table'=>'giftbag_appoint'),
    'yxd_services_models_giftbagcard'              => array('db'=>'club','table'=>'giftbag_card'),
    'yxd_services_models_hunttopicclicktimes'      => array('db'=>'club','table'=>'hunt_topic_clicktimes'),
    'yxd_services_models_inform'                   => array('db'=>'club','table'=>'inform'),
    'yxd_services_models_like'                     => array('db'=>'club','table'=>'like'),
    'yxd_services_models_likelogs'                 => array('db'=>'club','table'=>'like_logs'),
    'yxd_services_models_loginipblacklist'         => array('db'=>'club','table'=>'login_ip_blacklist'),
    'yxd_services_models_mobileblacklist'          => array('db'=>'club','table'=>'mobile_blacklist'),
    'yxd_services_models_mongolog'                 => array('db'=>'club','table'=>'mongolog'),
    'yxd_services_models_noticesetting'            => array('db'=>'club','table'=>'notice_setting'),
    'yxd_services_models_praise'                   => array('db'=>'club','table'=>'praise'),
    'yxd_services_models_sharelimit'               => array('db'=>'club','table'=>'share_limit'),
    'yxd_services_models_shopcate'                 => array('db'=>'club','table'=>'shop_cate'),
    'yxd_services_models_shopgoods'                => array('db'=>'club','table'=>'shop_goods'),
    'yxd_services_models_shopgoodsaccount'         => array('db'=>'club','table'=>'shop_goods_account'),
    'yxd_services_models_systemmessage'            => array('db'=>'club','table'=>'system_message'),
    'yxd_services_models_systemmessagetpl'         => array('db'=>'club','table'=>'system_message_tpl'),
    'yxd_services_models_systemsetting'            => array('db'=>'club','table'=>'system_setting'),
    'yxd_services_models_systemusermessage'        => array('db'=>'club','table'=>'system_user_message'),
    'yxd_services_models_systemusermessagedeleted' => array('db'=>'club','table'=>'system_user_message_deleted'),
    'yxd_services_models_systemusermessagereaded'  => array('db'=>'club','table'=>'system_user_message_readed'),
    'yxd_services_models_task'                     => array('db'=>'club','table'=>'task'),
    'yxd_services_models_taskaccount'              => array('db'=>'club','table'=>'task_account'),
    'yxd_services_models_todayexchangeaccount'     => array('db'=>'club','table'=>'today_exchange_account'),
    'yxd_services_models_tuiguangaccount'          => array('db'=>'club','table'=>'tuiguang_account'),


    'yxd_services_models_adv'=>array('db'=>'cms','table'=>'adv'),
    'yxd_services_models_advapp'=>array('db'=>'cms','table'=>'adv_app'),
    'yxd_services_models_advstate'=>array('db'=>'cms','table'=>'adv_state'),
    'yxd_services_models_advuser'=>array('db'=>'cms','table'=>'adv_user'),
    'yxd_services_models_advpos'=>array('db'=>'cms','table'=>'advpos'),
    'yxd_services_models_appadv'=>array('db'=>'cms','table'=>'appadv'),
    'yxd_services_models_appadvactivestat'=>array('db'=>'cms','table'=>'appadv_active_stat'),
    'yxd_services_models_appadvstat'=>array('db'=>'cms','table'=>'appadv_stat'),
    'yxd_services_models_article'=>array('db'=>'cms','table'=>'article'),
    'yxd_services_models_articlerecommendgame'=>array('db'=>'cms','table'=>'article_recommendgame'),
    //'yxd_services_models_'=>array('db'=>'cms','table'=>'comment'),
    //'yxd_services_models_'=>array('db'=>'cms','table'=>'comment_operator'),
    'yxd_services_models_configs'=>array('db'=>'cms','table'=>'configs'),
    'yxd_services_models_countone'=>array('db'=>'cms','table'=>'count_one'),
    'yxd_services_models_countthree'=>array('db'=>'cms','table'=>'count_three'),
    'yxd_services_models_counttwo'=>array('db'=>'cms','table'=>'count_two'),
    'yxd_services_models_feedback'=>array('db'=>'cms','table'=>'feedback'),
    'yxd_services_models_gamecrawl'=>array('db'=>'cms','table'=>'game_crawl'),
    'yxd_services_models_gamedownloadcount'=>array('db'=>'cms','table'=>'game_download_count'),
    'yxd_services_models_gamedownloadcountretry'=>array('db'=>'cms','table'=>'game_download_count_retry'),
    'yxd_services_models_gameexpedition'=>array('db'=>'cms','table'=>'game_expedition'),
    'yxd_services_models_gamemustplay'=>array('db'=>'cms','table'=>'game_mustplay'),
    'yxd_services_models_gamenotice'=>array('db'=>'cms','table'=>'game_notice'),
    'yxd_services_models_gamerecommend'=>array('db'=>'cms','table'=>'game_recommend'),
    'yxd_services_models_gamescore'=>array('db'=>'cms','table'=>'game_score'),
    'yxd_services_models_gametype'=>array('db'=>'cms','table'=>'game_type'),    

    'yxd_services_models_games'=>array('db'=>'cms','table'=>'games'),
    'yxd_services_models_gameslitpic'=>array('db'=>'cms','table'=>'games_litpic'),
    'yxd_services_models_gamesmap'=>array('db'=>'cms','table'=>'games_map'),
    'yxd_services_models_gamesschemes'=>array('db'=>'cms','table'=>'games_schemes'),
    'yxd_services_models_gamestag'=>array('db'=>'cms','table'=>'games_tag'),
    'yxd_services_models_gamesvideo'=>array('db'=>'cms','table'=>'games_video'),
    'yxd_services_models_gonglue'=>array('db'=>'cms','table'=>'gonglue'),
    'yxd_services_models_hotactivity'=>array('db'=>'cms','table'=>'hot_activity'),
    'yxd_services_models_mtype'=>array('db'=>'cms','table'=>'mtype'),
    'yxd_services_models_newgame'=>array('db'=>'cms','table'=>'newgame'),
    'yxd_services_models_news'=>array('db'=>'cms','table'=>'news'),
    'yxd_services_models_recommend'=>array('db'=>'cms','table'=>'recommend'),
    'yxd_services_models_searchtag'=>array('db'=>'cms','table'=>'search_tag'),
    'yxd_services_models_share'=>array('db'=>'cms','table'=>'share'),
    
    'yxd_services_models_tag'=>array('db'=>'cms','table'=>'tag'),
    'yxd_services_models_tools'=>array('db'=>'cms','table'=>'tools'),
    'yxd_services_models_version'=>array('db'=>'cms','table'=>'version'),
    'yxd_services_models_videos'=>array('db'=>'cms','table'=>'videos'),
    'yxd_services_models_videosgames'=>array('db'=>'cms','table'=>'videos_games'),
    'yxd_services_models_xyxcount'=>array('db'=>'cms','table'=>'xyx_count'),
    'yxd_services_models_xyxcountmapping'=>array('db'=>'cms','table'=>'xyx_count_mapping'),
    'yxd_services_models_xyxgame'=>array('db'=>'cms','table'=>'xyx_game'),
    'yxd_services_models_xyxgamepic'=>array('db'=>'cms','table'=>'xyx_game_pic'),
    'yxd_services_models_xyxpic'=>array('db'=>'cms','table'=>'xyx_pic'),
    'yxd_services_models_xyxtype'=>array('db'=>'cms','table'=>'xyx_type'),
    'yxd_services_models_zone'=>array('db'=>'cms','table'=>'zone'),
    'yxd_services_models_zt'=>array('db'=>'cms','table'=>'zt'),
    'yxd_services_models_ztgames'=>array('db'=>'cms','table'=>'zt_games'),

);