<?php
return array(
    'module_name'  => 'v4_statistics',
    'module_alias' => 'v4统计管理',
    'module_icon'  => 'ios',
    'default_url'=>'v4statistics/account/statistics',
    'child_menu' => array(
        array('name'=>'App日新增','url'=>'v4statistics/account/statistics'),
        array('name'=>'App日活跃','url'=>'v4statistics/account/day'),
        array('name'=>'我的游戏排行前10','url'=>'v4statistics/account/gametop'),
        array('name'=>'用户性别','url'=>'v4statistics/account/sex'),
        array('name'=>'用户年龄','url'=>'v4statistics/account/age'),
        array('name'=>'广告统计','url'=>'v4statistics/account/adv'),
        array('name'=>'CMS后台管理','url'=>'v4statistics/CMS/list'),
        array('name'=>'任务总数','url'=>'v4statistics/task/taskcount'),
 //       array('name'=>'任务查看/任务完成数','url'=>'v4statistics/task/taskselect'),
        array('name'=>'登录统计','url'=>'v4statistics/account/login'),
 //       array('name'=>'搜索关键字前十','url'=>'v4statistics/account/search'),
 //       array('name'=>'活动详情查看前十','url'=>'v4statistics/account/activity'),
        array('name'=>'CMS广告统计','url'=>'v4statistics/CMS/list'),
//         array('name'=>'游币发放与消耗','url'=>'v4statistics/appaccount/money-consume'),
        array('name'=>'钻石发放与消耗','url'=>'v4statistics/appaccount/diamonds-consume'),
        array('name'=>'礼包领取','url'=>'v4statistics/appaccount/package'),
        array('name'=>'礼包消耗钻石/游币','url'=>'v4statistics/appaccount/package-consume'),
        array('name'=>'商品兑换','url'=>'v4statistics/appaccount/good'),
        array('name'=>'商品消耗钻石/游币','url'=>'v4statistics/appaccount/good-consume'),
        array('name'=>'任务发放钻石','url'=>'v4statistics/appaccount/task-diamonds'),
        array('name'=>'任务钻石排行榜','url'=>'v4statistics/appaccount/task-diamonds-rank'),
        array('name'=>'挖宝活动钻石统计','url'=>'v4statistics/appaccount/count-dig'),
        array('name'=>'一元夺宝钻石统计','url'=>'v4statistics/appaccount/count-yiyuan'),
        array('name'=>'新用户任务参与度','url'=>'v4statistics/appaccount/excel-compare'),
    ),
    'extra_node'=>array(
        array('name'=>'全部统计模块','url'=>'v4statistics/*'),
    )
);